name: Workflow lors d'un push3
on: push
jobs:
  mon_job:
    outputs:
      statut: ${{steps.test.outcome}}
    name: Build teste et run mon app
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code
        uses: actions/checkout@v4
      - name: cache npm
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
        #voir aussi: le cache de actions/setup-node
        #-name Setup Node.js
        # uses: actions/setup-node@v4
        #with:
        # cache: "npm"
      - name: installation des nodes_modules #(selement si il sont pas déja présent)
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: build
        run: npm run build
      - id: test
        name: set test
        run: npm run test
        continue-on-error: true
      - name: start
        run: npm run start
      - name: Sommaire
        run: echo "# Résumé du step" >> $GITHUB_STEP_SUMMARY

  mon_deuxieme_job:
    name: if
    runs-on: ubuntu-latest
    needs: mon_job
    steps:
      - name: test
        run: echo "$NEEDS_JSON"
        env:
          NEEDS_JSON: ${{toJSON(needs.mon_job.outputs.statut)}}


