name: Workflow lors d'un push2
on: push
jobs:
  mon_job:
    name: Build teste et run mon app
    runs-on: ubuntu-latest
    outputs:
      sortie1: ${{steps.test}}
    steps:
      - name: récupérer le code
        uses: actions/checkout@v4
      - name: cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}

        #voir aussi: le cache de actions/setup-node
        #-name Setup Node.js
        # uses: actions/setup-node@v4
        #with:
        # cache: "npm"
      - name: installation des nodes_modules
        run: npm ci
      - name: build
        run: npm run build
      - id: test
        name: set test
        run: |
          npm run test
      - name: start
        run: npm run start
      - name: Sommaire
        run: echo "# Résumé du step" >> $GITHUB_STEP_SUMMARY

  mon_deuxieme_job:
    name: if
    runs-on: ubuntu-latest
    needs: mon_job
    steps:
      - name: test
        run: echo "$NEEDS_JSON"
        env:
          NEEDS_JSON: ${{toJSON(needs)}}
