name: worflow qui se déclenche lors de la création d'un issue
on:
  issues:
    types:
      - opened

jobs:
  commentaire:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE_URL  --body  "mERCI D'AVOIR OUVETRT CETTE ISSUE"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}} #github.token
          ISSUE_URL:  ${{ github.event.issue.html_url}}
  output:
    runs-on: ubuntu-latest
    steps:
      - name: sans variable d'env
        run: echo ouvelle issue - {{github.event.issue.title}}
      - name: avec variable d'env
        env:
          TITRE: ${{github.event.issue.title}}
        run: |
          echo Nouvelle issue = "$TITRE"
          echo "L'utilisateur d'une variable d'en intermédiaire atténue le risque d'injection de code"
